name: Rodando Testes de Regressão com Push

on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      browser:
        description: "Navegador para rodar os testes"
        required: false
        default: chrome
        type: choice
        options:
          - chrome
          - firefox
          - edge
          - electron

jobs:
  cypress-run:
    runs-on: ubuntu-24.04
    steps:
      - name: Baixando projeto
        uses: actions/checkout@v4

      - name: Rodar Teste
        uses: cypress-io/github-action@v6
        with:
          browser: ${{ github.event.inputs.browser || 'chrome' }}

      - name: Upload screenshots
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots

      - name: Upload mochawesome report
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: mochawesome-report
          path: mochawesome-report
          retention-days: 3